@HOST_STRAPI_INFORMATION = http://localhost:1337
@HOST = localhost:8082
GET {{HOST_STRAPI_INFORMATION}}/api/courses
    ?populate[thumbnail]=*
    &populate[course_high_light]=*
    &populate[advisors]=*
    &populate[categories]=*
    &populate[SEO][populate][shareImage][populate]=*
    &populate[video_content]=*
    &populate[video_preview]=*
    &populate[file]=* HTTP/1.1
Content-Type: application/json
Authorization: Bearer 6102511ec9d936311659e59bd511783c8a1f3b4b00f47b27fbc16df3a4d2594924189cfa0412d435966fc188b6573e7a378323537e3d67b3cdbe87a0791012aa8425bd11f70266afa897ec5cb1b82dbb57529da17f273d94ec336b93c0a5cf9b056f1d52ba6d9576685227508c4736f8d06a9158d37ea665fd07f5a81bb6e72e

###

GET http://{{HOST}}/course-listener/api/v1/courses HTTP/1.1
Content-Type: application/json

###


GET http://{{HOST}}/course-listener/api/v1/courses/1 HTTP/1.1
Content-Type: application/json

###


GET http://{{HOST}}/course-listener/api/v1/courses/slug/test-course-1 HTTP/1.1
Content-Type: application/json