package constants

const (
	PATH_STRAPI_COURSE              = "PATH_STRAPI_COURSE"
	HOST_STRAPI_SERVICE             = "HOST_STRAPI_SERVICE"
	PATH_STRAPI_INFORMATION_GATEWAY = "PATH_STRAPI_INFORMATION_GATEWAY"
)
